project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - homeworks/Homework_1.qmd
      - homeworks/Homework_2.qmd
      - homeworks/Homework_3.qmd
      - homeworks/Homework_4.qmd
      - homeworks/Homework_5.qmd
